# site properties and page defaults
title: Machado Lab
subtitle: Evolutionary Genomics
description: A website for the Machado lab using an easy-to-use, flexible website template for labs, with automatic citations, GitHub tag imports, pre-built components, and more.
logo-text: false
header: images/background-1.jpg
footer: images/footer.jpg
proofer: false

# site social media and other links
links:
  email: machado@umd.edu
  orcid: 0000-0003-1546-7415
  google-scholar: 0uj4niwAAAAJ
  github: Machado-Lab-UMD

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
