- id: doi:10.7554/eLife.32822
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
- id: doi.org/10.1038/s41467-021-20957-3
  image: https://www.nature.com/articles/s41467-021-20957-3/figures/3
- id: doi.org/10.1111/evo.13809
  image: 
- id: doi.org/10.1093/isd/ixaa005
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/isd/4/2/10.1093_isd_ixaa005/3/m_ixaa005f0001.jpeg?Expires=1744831066&Signature=Fx~2yJQvm1e4Dwm7Sf67S0Bqe3yVAHzGMbYsYi~ONxrGK3Y4opeUvc3RDEHOvfz2OMO7lVmX9bLF75iZ591v2twoMkUmfV6HJd0AM5k4udQ~FYoXtR3NAgZZ~odASWlnOy71X5DUHI7B8XVVvNw3ihjbJLf98j4sU0pX4sRZ1gm-E-c9cg5mTBpsTrxVWISfwyaxom--M-eeiEzHPShfCnFBs~79pQSd1jzZBWbSYssoGGBYWYWxErEJ~fhYei6btBb~K8i8W6lVN1O5fpJ3ceRQ5aXyb7P5t44iG39ZW49byLnUc2hGNMcruvc7WGY4UUjWIwPQpaza7jJLsb~9ew__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA