- id: doi:10.1038/s41467-021-20957-3
  image: https://www.nature.com/articles/s41467-021-20957-3/figures/3
- id: doi:10.1111/evo.13809
  image: 
- id: doi:10.1093/isd/ixaa005
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/isd/4/2/10.1093_isd_ixaa005/3/m_ixaa005f0001.jpeg?Expires=1744831066&Signature=Fx~2yJQvm1e4Dwm7Sf67S0Bqe3yVAHzGMbYsYi~ONxrGK3Y4opeUvc3RDEHOvfz2OMO7lVmX9bLF75iZ591v2twoMkUmfV6HJd0AM5k4udQ~FYoXtR3NAgZZ~odASWlnOy71X5DUHI7B8XVVvNw3ihjbJLf98j4sU0pX4sRZ1gm-E-c9cg5mTBpsTrxVWISfwyaxom--M-eeiEzHPShfCnFBs~79pQSd1jzZBWbSYssoGGBYWYWxErEJ~fhYei6btBb~K8i8W6lVN1O5fpJ3ceRQ5aXyb7P5t44iG39ZW49byLnUc2hGNMcruvc7WGY4UUjWIwPQpaza7jJLsb~9ew__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  # some paper returned by an ORCID that you don't want to keep at all
- id: doi:10.1101/2024.07.12.603340
  remove: true
- id: doi:10.1093/gbe/evae047 
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/gbe/16/3/10.1093_gbe_evae047/2/evae047f3.jpeg?Expires=1745709879&Signature=mmGfWjWZGr~3gZktEn11hmJHhGhgHwx~ygPpLh4q5u3cYN3LvVGwPBPcyAQmEtaV0T5RXVUdFK58aj7YLsAhihaoyQ5hjYqy3l~xs-JIhH9mY9GfCBOv4QAm2hpd6fRupuiTaL1Fjct8PQgZUn1rG9ZVP~oWGShRuOZ-plVEqV1OnLBpeIg8QbLWyvfQ-x0iDlW-q0UYDYZBwoOeOeGUGftEGpcsm~0AQyMP~mNhmkVB0oRN30d4aG3SWZsVdEyUTGn6v9cgk8-rNuiA52LhSgZtmwT35~smEtgXPRQ5rArHpRsY7ee6nyH-oMQhNICWd-e~fT32QS8I1FMAUq9nPg__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
- id: doi:10.1101/2025.04.20.649723
  image: images/highlight.png
  tags:
    - pre-print
